# Generated by Django 6.1.1 on 2026-09-13 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('type_etablissement', models.CharField(choices=[('LTP', 'Lycée Technique et Professionnel'), ('CFP', 'Centre de Formation Professionnelle'), ('CFPF', 'Centre de Formation Professionnelle et de Formation'), ('LTPA', 'Lycée Technique et Professionnel Agricole'), ('INPF', 'Institut National de Formation Professionnelle'), ('CNFPPSH', 'Centre National de Formation des Personnels')], max_length=10, verbose_name='Type')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('region', models.CharField(default="Amoron'i Mania", max_length=100, verbose_name='Région')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PCOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Code PCOP',
                'verbose_name_plural': 'Codes PCOP',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('unite', models.CharField(choices=[('Nombre', 'Nombre'), ('Pack', 'Pack'), ('Litre', 'Litre'), ('Jour', 'Jour'), ('Carte', 'Carte'), ('Pièce', 'Pièce'), ('Sac', 'Sac'), ('m3', 'Mètre cube')], max_length=20, verbose_name='Unité')),
                ('cible', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cible')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['sous_activite', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LigneBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_financement', models.CharField(choices=[('RPI', 'RPI'), ('FCE', 'FCE'), ('UNESCO', 'UNESCO'), ('Partenaire', 'Partenaire')], max_length=20, verbose_name='Source')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant prévu (Ar)')),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant réalisé (Ar)')),
                ('statut', models.CharField(choices=[('Planifié', 'Planifié'), ('Engagé', 'Engagé'), ('Liquidé', 'Liquidé'), ('Payé', 'Payé')], default='Planifié', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etablissement', verbose_name='Établissement')),
                ('pcop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pcop', verbose_name='Code PCOP')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne budgétaire',
                'verbose_name_plural': 'Lignes budgétaires',
                'ordering': ['etablissement', 'produit'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DRETFP', 'Administrateur DRETFP'), ('CHEF_ETAB', "Chef d'établissement"), ('AGENT', 'Agent'), ('FORMATEUR', 'Formateur'), ('LECTEUR', 'Lecture seule')], default='AGENT', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etablissement', verbose_name='Établissement')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('objectif', models.TextField(blank=True, verbose_name='Objectif')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programme', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['programme', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='SousActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activite', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Sous-activité',
                'verbose_name_plural': 'Sous-activités',
                'ordering': ['activite', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sousactivite', verbose_name='Sous-activité'),
        ),
    ]
