# Generated by Django 6.1.1 on 2026-09-14 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ['programme', 'libelle'], 'verbose_name': 'Activite', 'verbose_name_plural': 'Activites'},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['nom'], 'verbose_name': 'Etablissement', 'verbose_name_plural': 'Etablissements'},
        ),
        migrations.AlterModelOptions(
            name='lignebudgetaire',
            options={'ordering': ['etablissement', 'produit'], 'verbose_name': 'Ligne budgetaire', 'verbose_name_plural': 'Lignes budgetaires'},
        ),
        migrations.AlterModelOptions(
            name='sousactivite',
            options={'ordering': ['activite', 'libelle'], 'verbose_name': 'Sous-activite', 'verbose_name_plural': 'Sous-activites'},
        ),
        migrations.AlterField(
            model_name='activite',
            name='libelle',
            field=models.CharField(max_length=300, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='region',
            field=models.CharField(default="Amoron'i Mania", max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('LTP', 'Lycee Technique et Professionnel'), ('CFP', 'Centre de Formation Professionnelle'), ('CFPF', 'Centre de Formation Professionnelle et de Formation'), ('LTPA', 'Lycee Technique et Professionnel Agricole'), ('INPF', 'Institut National de Formation Professionnelle'), ('CNFPPSH', 'Centre National de Formation des Personnels')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='lignebudgetaire',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date debut'),
        ),
        migrations.AlterField(
            model_name='lignebudgetaire',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etablissement', verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='lignebudgetaire',
            name='montant_prevu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant prevu (Ar)'),
        ),
        migrations.AlterField(
            model_name='lignebudgetaire',
            name='montant_realise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant realise (Ar)'),
        ),
        migrations.AlterField(
            model_name='lignebudgetaire',
            name='statut',
            field=models.CharField(choices=[('Planifie', 'Planifie'), ('Engage', 'Engage'), ('Liquide', 'Liquide'), ('Paye', 'Paye')], default='Planifie', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='pcop',
            name='libelle',
            field=models.CharField(max_length=300, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='libelle',
            field=models.CharField(max_length=300, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sous_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sousactivite', verbose_name='Sous-activite'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(choices=[('Nombre', 'Nombre'), ('Pack', 'Pack'), ('Litre', 'Litre'), ('Jour', 'Jour'), ('Carte', 'Carte'), ('Piece', 'Piece'), ('Sac', 'Sac'), ('m3', 'Metre cube')], max_length=20, verbose_name='Unite'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etablissement', verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('DRETFP', 'Administrateur DRETFP'), ('CHEF_ETAB', "Chef d'etablissement"), ('AGENT', 'Agent'), ('FORMATEUR', 'Formateur'), ('LECTEUR', 'Lecture seule')], default='AGENT', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='libelle',
            field=models.CharField(max_length=200, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='sousactivite',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activite', verbose_name='Activite'),
        ),
        migrations.AlterField(
            model_name='sousactivite',
            name='libelle',
            field=models.CharField(max_length=300, verbose_name='Libelle'),
        ),
        migrations.CreateModel(
            name='DemandeReinitialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('message', models.TextField(blank=True, verbose_name='Message / Justification')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Traitee', 'Traitee'), ('Rejetee', 'Rejetee')], default='En attente', max_length=20, verbose_name='Statut')),
                ('nouveau_mot_de_passe', models.CharField(blank=True, max_length=100, verbose_name='Nouveau mot de passe (visible admin)')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de reinitialisation',
                'verbose_name_plural': 'Demandes de reinitialisation',
                'ordering': ['-date_demande'],
            },
        ),
    ]
