# Generated by Django 6.1.1 on 2026-09-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activite_options_alter_etablissement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=2027, verbose_name='Annee')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Valide', 'Valide'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Archive', 'Archive')], default='Brouillon', max_length=20, verbose_name='Statut')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etablissement', verbose_name='Etablissement')),
            ],
            options={
                'verbose_name': 'PTA',
                'verbose_name_plural': 'PTA',
                'ordering': ['-annee', 'etablissement'],
                'unique_together': {('etablissement', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ActivitePTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('statut', models.CharField(choices=[('Non commence', 'Non commence'), ('En cours', 'En cours'), ('Termine', 'Termine'), ('Annule', 'Annule'), ('Reporte', 'Reporte')], default='Non commence', max_length=20, verbose_name='Statut')),
                ('taux_avancement', models.IntegerField(default=0, verbose_name="Taux d'avancement (%)")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget prevu (Ar)')),
                ('budget_realise', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget realise (Ar)')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activite', verbose_name='Activite liee')),
                ('PTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pta', verbose_name='PTA')),
            ],
            options={
                'verbose_name': 'Activite PTA',
                'verbose_name_plural': 'Activites PTA',
                'ordering': ['ordre', 'date_debut', 'titre'],
            },
        ),
    ]
