# Generated by Django 6.1.1 on 2026-09-15 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pta_activitepta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitepta',
            name='PTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='core.pta', verbose_name='PTA'),
        ),
    ]
