# Generated by Django 6.1.1 on 2026-09-15 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activitepta_pta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('heure_debut', models.TimeField(verbose_name='Heure debut')),
                ('heure_fin', models.TimeField(verbose_name='Heure fin')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Creneau horaire',
                'verbose_name_plural': 'Creneaux horaires',
                'ordering': ['ordre', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la filiere')),
                ('niveau', models.CharField(choices=[('CAP', 'CAP'), ('BEP', 'BEP'), ('BAC', 'Baccalaureat'), ('AMB', 'Apprentissage Metiers de Base'), ('FPQ', 'Formation Professionnelle Qualifiante')], max_length=10, verbose_name='Niveau')),
                ('nb_apprenants', models.IntegerField(default=0, verbose_name='Nb apprenants')),
                ('duree_annees', models.IntegerField(default=2, verbose_name='Duree (annees)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.etablissement', verbose_name='Etablissement')),
            ],
            options={
                'verbose_name': 'Filiere',
                'verbose_name_plural': 'Filieres',
                'ordering': ['etablissement', 'code'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacite', models.IntegerField(default=30, verbose_name='Capacite')),
                ('type_salle', models.CharField(blank=True, max_length=50, verbose_name='Type de salle')),
                ('batiment', models.CharField(blank=True, max_length=100, verbose_name='Batiment')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='core.etablissement', verbose_name='Etablissement')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['etablissement', 'nom'],
                'unique_together': {('etablissement', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('matiere', models.CharField(max_length=200, verbose_name='Matiere / Module')),
                ('annee_scolaire', models.CharField(default='2026-2027', max_length=20, verbose_name='Annee scolaire')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.creneauhoraire', verbose_name='Creneau horaire')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='core.filiere', verbose_name='Filiere')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['jour', 'creneau__ordre'],
            },
        ),
    ]
