# Generated by Django 6.1.1 on 2026-09-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_creneauhoraire_filiere_salle_emploidutemps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandereinitialisation',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='demandereinitialisation',
            name='nouveau_mot_de_passe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nouveau mot de passe'),
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la matiere')),
                ('type_matiere', models.CharField(choices=[('Theorique', 'Theorique'), ('Pratique', 'Pratique'), ('Theorique et Pratique', 'Theorique et Pratique'), ('Sport', 'Education Physique et Sportive')], default='Theorique', max_length=30, verbose_name='Type')),
                ('heures_theorie', models.IntegerField(default=0, verbose_name='Heures theorie')),
                ('heures_pratique', models.IntegerField(default=0, verbose_name='Heures pratique')),
                ('coefficient', models.IntegerField(default=1, verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='core.filiere', verbose_name='Filiere')),
            ],
            options={
                'verbose_name': 'Matiere',
                'verbose_name_plural': 'Matieres',
                'ordering': ['filiere', 'code'],
                'unique_together': {('filiere', 'code')},
            },
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='matiere_lien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='core.matiere', verbose_name='Matiere liee'),
        ),
    ]
